"""Database package: declarative Base, ORM models, and session factories."""

from __future__ import annotations

from .base import Base
from .models import (
    AccessEvent,
    AuditLogEntry,
    Building,
    Camera,
    Case,
    CaseEvidence,
    CrossSiteLink,
    Device,
    Dispatch,
    EvalRun,
    Event,
    EvidenceRecord,
    FleetFinding,
    FleetSnapshot,
    Incident,
    IncidentStatusLog,
    ModelVersion,
    OncallShift,
    PlateSighting,
    Recording,
    Responder,
    SensorEvent,
    Signature,
    Site,
    SocShift,
    TrackedObject,
    User,
    Zone,
    case_incidents,
)
from .session import (
    async_session_factory,
    get_async_engine,
    get_session,
    get_sync_engine,
    sync_session_factory,
)

__all__ = [
    "Base",
    "Site",
    "Building",
    "Zone",
    "Camera",
    "Signature",
    "TrackedObject",
    "Event",
    "Incident",
    "IncidentStatusLog",
    "Case",
    "CaseEvidence",
    "case_incidents",
    "AccessEvent",
    "Device",
    "SensorEvent",
    "Recording",
    "User",
    "AuditLogEntry",
    "EvidenceRecord",
    "ModelVersion",
    "EvalRun",
    "Responder",
    "OncallShift",
    "Dispatch",
    "SocShift",
    "FleetSnapshot",
    "FleetFinding",
    "PlateSighting",
    "CrossSiteLink",
    "async_session_factory",
    "sync_session_factory",
    "get_async_engine",
    "get_sync_engine",
    "get_session",
]
